import Joi from "joi";

const PG_INT_MAX = 2147483647;

const fileSchema = Joi.object({
  name: Joi.string().required(),
  path: Joi.string().required(),
  dateAdded: Joi.date().iso().required(),
});

export const CreateMachineSchema = Joi.object({
  name: Joi.string().required(),
  machineNumber: Joi.number().integer().positive().max(PG_INT_MAX).required(),
  serialNumber: Joi.string().optional().allow("", null),
  yearOfManufacture: Joi.number().integer().min(1900).max(2100).optional().allow(null),
  clampingForce: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  injectionWeight: Joi.string().optional().allow("", null),
  description: Joi.string().optional().allow("", null),
  pictures: Joi.array().items(fileSchema).optional(),
  documents: Joi.array().items(fileSchema).optional(),
  maxMoldWeight: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  maxMoldWidth: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  maxMoldHeight: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  minMoldThickness: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  maxMoldThickness: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  centeringRingFixedSide: Joi.string().optional().allow("", null),
  centeringRingMovingSide: Joi.string().optional().allow("", null),
  controlSystem: Joi.string().optional().allow("", null),
  serviceInterval: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  lastServiceDone: Joi.date().iso().optional().allow(null),
  automaticMode: Joi.boolean().optional().default(false),
  semiAutomaticMode: Joi.boolean().optional().default(false),
  manualMode: Joi.boolean().optional().default(false),
  workHoursCounter: Joi.number().integer().max(PG_INT_MAX).optional().default(0),
  pieceCounter: Joi.number().integer().max(PG_INT_MAX).optional().default(0),
  scrapCounter: Joi.number().integer().max(PG_INT_MAX).optional().default(0),
  workPermit: Joi.boolean().optional().default(false),
  availabilityStatusId: Joi.number().integer().optional().allow(null),
  createdBy: Joi.string().optional().allow("", null),
  updatedBy: Joi.string().optional().allow("", null),
});

export const UpdateMachineSchema = Joi.object({
  id: Joi.string().uuid().optional(),
  name: Joi.string().optional(),
  machineNumber: Joi.number().integer().positive().max(PG_INT_MAX).optional(),
  serialNumber: Joi.string().optional().allow("", null),
  yearOfManufacture: Joi.number().integer().min(1900).max(2100).optional().allow(null),
  clampingForce: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  injectionWeight: Joi.string().optional().allow("", null),
  description: Joi.string().optional().allow("", null),
  pictures: Joi.array().items(fileSchema).optional(),
  documents: Joi.array().items(fileSchema).optional(),
  maxMoldWeight: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  maxMoldWidth: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  maxMoldHeight: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  minMoldThickness: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  maxMoldThickness: Joi.number().integer().positive().max(PG_INT_MAX).optional().allow(null),
  centeringRingFixedSide: Joi.string().optional().allow("", null),
  centeringRingMovingSide: Joi.string().optional().allow("", null),
  controlSystem: Joi.string().optional().allow("", null),
  serviceInterval: Joi.number().integer().max(PG_INT_MAX).optional().allow(null),
  lastServiceDone: Joi.date().iso().optional().allow(null),
  automaticMode: Joi.boolean().optional(),
  semiAutomaticMode: Joi.boolean().optional(),
  manualMode: Joi.boolean().optional(),
  workHoursCounter: Joi.number().integer().max(PG_INT_MAX).optional(),
  pieceCounter: Joi.number().integer().max(PG_INT_MAX).optional(),
  scrapCounter: Joi.number().integer().max(PG_INT_MAX).optional(),
  workPermit: Joi.boolean().optional(),
  availabilityStatusId: Joi.number().integer().optional().allow(null),
  createdBy: Joi.string().optional().allow("", null),
  updatedBy: Joi.string().optional().allow("", null),
  createdAt: Joi.date().iso().optional(),
  updatedAt: Joi.date().iso().optional(),
  availabilityStatusName: Joi.string().optional().allow("", null),
});